# Generated by Django 3.1.7 on 2021-06-27 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('years_active', models.IntegerField()),
                ('nationality', models.CharField(max_length=50)),
                ('imageField', models.URLField(blank=True)),
                ('twitterAccount', models.CharField(blank=True, max_length=255)),
                ('instagramAccount', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('website', models.URLField()),
                ('imageField', models.URLField(blank=True)),
                ('twitterAccount', models.CharField(blank=True, max_length=255)),
                ('instagramAccount', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Undefined', max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('rating', models.FloatField()),
                ('imageField', models.URLField(blank=True)),
                ('published_date', models.DateField(null=True)),
                ('cast', models.ManyToManyField(to='app.Actor')),
                ('director', models.ManyToManyField(to='app.Director')),
                ('genre', models.ManyToManyField(to='app.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('website', models.URLField()),
                ('imageField', models.URLField(blank=True)),
                ('twitterAccount', models.CharField(blank=True, max_length=255)),
                ('instagramAccount', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageField', models.URLField(blank=True)),
                ('favorite_genres', models.ManyToManyField(to='app.Genre')),
                ('favorite_movies', models.ManyToManyField(related_name='user_favorite_movies', to='app.Movie')),
                ('movies_watched', models.ManyToManyField(related_name='user_watched_movies', to='app.Movie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('want_to_watch', models.ManyToManyField(related_name='user_wanttowatch_movies', to='app.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='producer',
            field=models.ManyToManyField(to='app.Producer'),
        ),
    ]
